name: flutter_inappwebview_forge_internal_annotations
description: Internal annotations used by the generator of flutter_inappwebview_forge plugin
version: 1.0.0
repository: https://github.com/emirkanacar/flutter_inappwebview
issue_tracker: https://github.com/emirkanacar/flutter_inappwebview/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dev_dependencies:
  test: ^1.31.1
