name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.7
  source_gen: ^4.2.4
  analyzer: ^9.0.0
  collection: ^1.19.1
  flutter_inappwebview_forge_internal_annotations: ^1.0.0
    # path: ../flutter_inappwebview_forge_internal_annotations

dev_dependencies:
  build_runner: ^2.15.1
  build_test: ^3.5.16
  test: ^1.31.1
