import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_inappwebview_forge/flutter_inappwebview_forge.dart';
import 'package:integration_test/integration_test.dart';

const _runDiagnostic = bool.fromEnvironment(
  'RUN_ANDROID_2819_RENDERER_DIAGNOSTIC',
);

const _useHybridComposition = bool.fromEnvironment(
  'ANDROID_2819_USE_HYBRID_COMPOSITION',
  defaultValue: true,
);

// This is the iframe URL generated by the upstream IFramely Vimeo page for
// https://vimeo.com/783455878. The direct player avoids making the diagnostic
// depend on IFramely's separate oEmbed fetch endpoint.
const _pageUrl = 'https://player.vimeo.com/video/783455878?app_id=122963';
const _sentinelKey = ValueKey<String>('android-2819-diagnostic-sentinel');
const _webViewKey = ValueKey<String>('android-2819-diagnostic-webview');

Future<bool> _waitFor<T>(
  WidgetTester tester,
  Completer<T> event, {
  int seconds = 60,
}) async {
  for (var second = 0; second < seconds && !event.isCompleted; second++) {
    await tester.pump(const Duration(seconds: 1));
  }
  return event.isCompleted;
}

Future<Object?> _runScript(InAppWebViewController controller, String source) {
  return controller.evaluateJavascript(source: source);
}

Future<Object?> _addDiagnosticOverlay(InAppWebViewController controller) {
  return _runScript(controller, r'''
(function() {
  var existing = document.getElementById('__forge_2819_overlay');
  if (existing) existing.remove();
  var banner = document.createElement('div');
  banner.id = '__forge_2819_overlay';
  banner.textContent = 'Forge #2819 diagnostic overlay';
  banner.style.cssText = [
    'position:fixed',
    'top:0',
    'left:0',
    'right:0',
    'z-index:2147483647',
    'padding:12px',
    'background:#b71c1c',
    'color:white',
    'font:700 16px sans-serif',
    'text-align:center',
    'pointer-events:none'
  ].join(';');
  (document.body || document.documentElement).appendChild(banner);
  var button = document.createElement('button');
  button.id = '__forge_2819_fullscreen';
  button.textContent = 'Enter fullscreen';
  button.style.cssText = [
    'position:fixed',
    'top:72px',
    'right:12px',
    'z-index:2147483647',
    'padding:12px 16px',
    'background:#1565c0',
    'color:white',
    'border:2px solid white',
    'border-radius:6px',
    'font:700 16px sans-serif',
    'pointer-events:auto'
  ].join(';');
  button.addEventListener('click', function() {
    var video = document.querySelector('video');
    if (!video) return;
    video.muted = true;
    var playback = video.play();
    if (playback && playback.catch) playback.catch(function() {});
    var request = video.requestFullscreen ||
        video.webkitRequestFullscreen ||
        video.webkitEnterFullscreen;
    if (request) request.call(video);
  });
  (document.body || document.documentElement).appendChild(button);
  return JSON.stringify({
    readyState: document.readyState,
    videos: document.querySelectorAll('video').length,
    iframes: document.querySelectorAll('iframe').length,
    overlay: true,
    fullscreenButton: true
  });
})()
''');
}

// Opt-in diagnostic for issue #2819. It loads the Vimeo iframe generated by
// the exact upstream IFramely page, adds a page overlay, and enters fullscreen
// through a real platform-view gesture. The operator can then disable network
// and show the player popup. A renderer-loss callback must restore the host
// fullscreen state without terminating the Flutter activity. A clean run
// without that callback is evidence that the exact provider failure was not
// reproduced.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets(
    'Android #2819 fullscreen renderer-loss diagnostic',
    (WidgetTester tester) async {
      final controllerCompleter = Completer<InAppWebViewController>();
      final pageLoaded = Completer<void>();
      final enteredFullscreen = Completer<void>();
      final exitedFullscreen = Completer<void>();
      var rendererGone = false;
      var rendererDidCrash = false;
      Object? rendererPriority;

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Stack(
              children: [
                InAppWebView(
                  key: _webViewKey,
                  initialUrlRequest: URLRequest(url: WebUri(_pageUrl)),
                  initialSettings: InAppWebViewSettings(
                    javaScriptEnabled: true,
                    mediaPlaybackRequiresUserGesture: false,
                    allowsInlineMediaPlayback: false,
                    useHybridComposition: _useHybridComposition,
                    useOnRenderProcessGone: true,
                  ),
                  onWebViewCreated: controllerCompleter.complete,
                  onLoadStop: (controller, url) {
                    if (!pageLoaded.isCompleted) {
                      pageLoaded.complete();
                    }
                  },
                  onEnterFullscreen: (controller) {
                    if (!enteredFullscreen.isCompleted) {
                      enteredFullscreen.complete();
                    }
                  },
                  onExitFullscreen: (controller) {
                    if (!exitedFullscreen.isCompleted) {
                      exitedFullscreen.complete();
                    }
                  },
                  onRenderProcessGone: (controller, detail) {
                    rendererGone = true;
                    rendererDidCrash = detail.didCrash;
                    rendererPriority = detail.rendererPriorityAtExit;
                    debugPrint(
                      'Android #2819 renderer gone: '
                      'didCrash=$rendererDidCrash '
                      'priority=$rendererPriority',
                    );
                  },
                ),
                const Positioned(
                  left: 0,
                  right: 0,
                  bottom: 0,
                  child: ColoredBox(
                    color: Colors.black87,
                    child: Padding(
                      padding: EdgeInsets.all(8),
                      child: Text(
                        '2819: enter Vimeo fullscreen, disable network, show overlay',
                        key: _sentinelKey,
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );

      final controller = await controllerCompleter.future;
      expect(
        await _waitFor(tester, pageLoaded),
        isTrue,
        reason: 'The exact #2819 Vimeo page did not finish loading.',
      );

      final overlayResult = await _addDiagnosticOverlay(controller);
      final pageProbe = await _runScript(controller, r'''
JSON.stringify({
  readyState: document.readyState,
  title: document.title,
  videos: document.querySelectorAll('video').length,
  iframes: document.querySelectorAll('iframe').length,
  url: location.href
})
''');
      debugPrint(
        'Android #2819 READY: hybrid=$_useHybridComposition '
        'overlay=$overlayResult probe=$pageProbe '
        'manualSteps="disable Wi-Fi/data after fullscreen; show the player '
        'popup; wait for a white/black surface"',
      );

      final webViewRenderBox = tester.renderObject<RenderBox>(
        find.byKey(_webViewKey),
      );
      await tester.tapAt(
        webViewRenderBox.localToGlobal(Offset.zero) +
            Offset(webViewRenderBox.size.width - 48, 96),
      );
      await tester.pump();

      await _waitFor(tester, enteredFullscreen, seconds: 90);
      final entered = enteredFullscreen.isCompleted;
      final exited = exitedFullscreen.isCompleted;
      if (entered) {
        debugPrint(
          'Android #2819 INTERACTIVE_FULLSCREEN_WINDOW: '
          'disable network and open the Vimeo popup/menu now',
        );
      }
      if (!entered) {
        debugPrint(
          'Android #2819 fullscreen was not entered during the interactive '
          'window; no renderer-loss conclusion is possible.',
        );
      }

      if (entered && !rendererGone && !exited) {
        await _waitFor(tester, exitedFullscreen, seconds: 180);
      }

      Object? fullscreenState;
      try {
        fullscreenState = await controller.isInFullscreen();
      } catch (error) {
        fullscreenState = 'query-error:${error.runtimeType}';
      }

      debugPrint(
        'Android #2819 diagnostic: entered=$entered '
        'exited=${exitedFullscreen.isCompleted} rendererGone=$rendererGone '
        'didCrash=$rendererDidCrash priority=$rendererPriority '
        'fullscreenState=$fullscreenState',
      );
      expect(find.byKey(_sentinelKey), findsOneWidget);
    },
    skip: !_runDiagnostic || !Platform.isAndroid,
    timeout: const Timeout(Duration(minutes: 4)),
  );
}
